# Checkpoint 1 za 09.03. i 16.03.2023 :

### Odabrati skup podataka (objaviti na forumu) i napraviti osnovnu analizu podataka u pythonu:

<strong>učitati iz csv u dataframe (pandas)<br>
pregled prvih 5 redaka<br>
veličina skupa<br>
nazivi stupaca<br>
broj nedostajućih vrijednosti po stupcu (.isna)<br>
jedinstvene vrijednosti (.unique())<br>
ispis tipova podataka (.dtypes)<br>
frekvencije vrijednosti po stupcu (petlja, data[column].value_counts()) </strong><br>
    
    
### Pitanja:<br>
    
<strong>Da li je skup podataka dovoljno velik?<br>
Da li skup ima dovoljno različite podatke?<br>
Da li skup ima vremensku dimenziju?<br>
Da li skup ima kvantitativne i kvalitativne podatke?<br>
Da li skup ima puno nedostajućih vrijednosti?<br>
Skup, rezultate analize i odgovore na pitanja kratko prezentirati (5 min.) na vježbama 09.03. i 16.03.</strong>

### Instalacija i učitavanje paketa

In [1]:
import pandas as pd

df = pd.read_csv('anime.csv')

### Ispis prvih 5 redaka

In [2]:
df.head()

,MAL_ID,Name,Score,Genres,Type,Episodes,Aired,Producers,Licensors,Studios,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,"Apr 3, 1998 to Apr 24, 1999",Bandai Visual,"Funimation, Bandai Entertainment",Sunrise,...,229170,182126,131625,62330,20688,8904,3184,1357,741,1580
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,1-Sep-01,"Sunrise, Bandai Visual",Sony Pictures Entertainment,Bones,...,30043,49201,49505,22632,5805,1877,577,221,109,379
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,"Apr 1, 1998 to Sep 30, 1998",Victor Entertainment,"Funimation, Geneon Entertainment USA",Madhouse,...,50229,75651,86142,49432,15376,5838,1965,664,316,533
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,"Jul 2, 2002 to Dec 24, 2002","TV Tokyo, Bandai Visual, Dentsu, Victor Entert...","Funimation, Bandai Entertainment",Sunrise,...,2182,4806,10128,11618,5709,2920,1083,353,164,131
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,"Sep 30, 2004 to Sep 29, 2005","TV Tokyo, Dentsu",No license,Toei Animation,...,312,529,1242,1713,1068,634,265,83,50,27

### Veličina skupa

In [3]:
df.shape

(17278, 32)

### Nazivi stupaca

In [4]:
list(df.columns)

['MAL_ID',
 'Name',
 'Score',
 'Genres',
 'Type',
 'Episodes',
 'Aired',
 'Producers',
 'Licensors',
 'Studios',
 'Source',
 'Duration',
 'Rating',
 'Ranked',
 'Popularity',
 'Members',
 'Favorites',
 'Watching',
 'Completed',
 'On-Hold',
 'Dropped',
 'Plan to Watch',
 'Score-10',
 'Score-9',
 'Score-8',
 'Score-7',
 'Score-6',
 'Score-5',
 'Score-4',
 'Score-3',
 'Score-2',
 'Score-1']

### Broj nedostajućih vrijednosti po stupcu

In [5]:
df.isnull().sum()

MAL_ID           0
Name             0
Score            0
Genres           0
Type             0
Episodes         0
Aired            0
Producers        0
Licensors        0
Studios          0
Source           0
Duration         0
Rating           0
Ranked           0
Popularity       0
Members          0
Favorites        0
Watching         0
Completed        0
On-Hold          0
Dropped          0
Plan to Watch    0
Score-10         0
Score-9          0
Score-8          0
Score-7          0
Score-6          0
Score-5          0
Score-4          0
Score-3          0
Score-2          0
Score-1          0
dtype: int64

### Broj jedinsvenih vrijednosti po stupcu

In [6]:
for column in df.columns:
    unique_values = len(df[column].unique())
    print(f"Unique values in column {column}: {unique_values}")

Unique values in column MAL_ID: 17278
Unique values in column Name: 17277
Unique values in column Score: 533
Unique values in column Genres: 4982
Unique values in column Type: 7
Unique values in column Episodes: 201
Unique values in column Aired: 11889
Unique values in column Producers: 3758
Unique values in column Licensors: 231
Unique values in column Studios: 1072
Unique values in column Source: 15
Unique values in column Duration: 313
Unique values in column Rating: 7
Unique values in column Ranked: 10458
Unique values in column Popularity: 11650
Unique values in column Members: 9407
Unique values in column Favorites: 1540
Unique values in column Watching: 3579
Unique values in column Completed: 7821
Unique values in column On-Hold: 2915
Unique values in column Dropped: 3035
Unique values in column Plan to Watch: 6965
Unique values in column Score-10: 3379
Unique values in column Score-9: 3645
Unique values in column Score-8: 4515
Unique values in column Score-7: 4932
Unique values in column Score-6: 4235
Unique values in column Score-5: 3287
Unique values in column Score-4: 2234
Unique values in column Score-3: 1506
Unique values in column Score-2: 1110
Unique values in column Score-1: 1083

### Vrste podataka

In [7]:
df.dtypes

MAL_ID             int64
Name              object
Score            float64
Genres            object
Type              object
Episodes           int64
Aired             object
Producers         object
Licensors         object
Studios           object
Source            object
Duration          object
Rating            object
Ranked             int64
Popularity         int64
Members            int64
Favorites          int64
Watching           int64
Completed          int64
On-Hold            int64
Dropped            int64
Plan to Watch      int64
Score-10           int64
Score-9            int64
Score-8            int64
Score-7            int64
Score-6            int64
Score-5            int64
Score-4            int64
Score-3            int64
Score-2            int64
Score-1            int64
dtype: object

### Frekvencije vrijednosti po stupcu

In [9]:
value_counts = [df[col].value_counts() for col in df.columns]
value_counts

[1        1
 32789    1
 32768    1
 32772    1
 32773    1
         ..
 9423     1
 9424     1
 9426     1
 9433     1
 48480    1
 Name: MAL_ID, Length: 17278, dtype: int64,
 Hinamatsuri                        2
 Cowboy Bebop                       1
 Jitensha-hen                       1
 Future Card Buddyfight Triple D    1
 Lina Poe Poe                       1
                                   ..
 Koko ni Iru                        1
 Seupideuwang Beongae               1
 Pururun! Shizuku-chan              1
 A-jang.com                         1
 Wan Jie Shen Zhu 3rd Season        1
 Name: Name, Length: 17277, dtype: int64,
 6.509999    4869
 6.480000      74
 6.300000      72
 6.310000      72
 6.520000      71
             ...
 3.190000       1
 4.200000       1
 4.350000       1
 3.320000       1
 4.060000       1
 Name: Score, Length: 533, dtype: int64,
 Hentai                                           967
 Music                                            778
 Comedy                                           663
 Kids                                             400
 Kids, Music                                      233
                                                 ...
 Comedy, Hentai, Romance, Yuri                      1
 Slice of Life, Drama, Magic, Romance, Shounen      1
 Horror, Super Power, Drama, Romance, Shoujo        1
 Action, Game, Adventure, Martial Arts              1
 Martial Arts, Fantasy                              1
 Name: Genres, Length: 4982, dtype: int64,
 TV         4879
 OVA        3864
 Movie      2999
 Special    2211
 ONA        1842
 Music      1464
 Unknown      19
 Name: Type, dtype: int64,
 1      8645
 12     1440
 2      1366
 13      767
 3       629
        ...
 182       1
 113       1
 215       1
 192       1
 160       1
 Name: Episodes, Length: 201, dtype: int64,
 Unknown                         181
 2005                             57
 2004                             49
 2003                             46
 2006                             45
                                ...
 Oct 1, 1993 to Feb 1, 1994        1
 Oct 2, 1989 to Jan 28, 1991       1
 19-Jul-61                         1
 Feb 12, 2010 to May 14, 2010      1
 Mar 17, 2021 to ?                 1
 Name: Aired, Length: 11889, dtype: int64,
 Home production                                                                                7593
 NHK                                                                                             621
 Pink Pineapple                                                                                  183
 Sanrio                                                                                          160
 Bandai Visual                                                                                   117
                                                                                                ...
 Milky Animation Label, MS Pictures, Anime Antenna Iinkai                                          1
 TV Tokyo, Dentsu, Pony Canyon, Kodansha, DAX Production, Sakura Create                            1
 Aniplex, Square Enix, Mainichi Broadcasting System                                                1
 Aniplex, Square Enix, Mainichi Broadcasting System, Movic, ASCII Media Works, Sakura Create       1
 Suiseisha, blackflag                                                                              1
 Name: Producers, Length: 3758, dtype: int64,
 No license                                     13333
 Funimation                                       882
 Sentai Filmworks                                 652
 Media Blasters                                   206
 Discotek Media                                   194
                                                ...
 Bandai                                             1
 Nozomi Entertainment, Kadokawa Pictures USA        1
 Sentai Filmworks, Crunchyroll                      1
 ADV Films, Funimation, OLM Digital                 1
 iQIYI                                              1
 Name: Licensors, Length: 231, dtype: int64,
 Unknown                        6941
 Toei Animation                  751
 Sunrise                         473
 J.C.Staff                       351
 Madhouse                        324
                                ...
 Tokyo Media Connections           1
 Gainax, Group TAC                 1
 Studio Unicorn                    1
 Public & Basic, Ripple Film       1
 Irawias                           1
 Name: Studios, Length: 1072, dtype: int64,
 Original         8704
 Manga            3741
 Visual novel      989
 Game              856
 Light novel       731
 Other             584
 Novel             482
 Music             315
 4-koma manga      282
 Web manga         246
 Picture book      146
 Book              111
 Card game          64
 Digital manga      15
 Radio              12
 Name: Source, dtype: int64,
 24 min. per ep.          1723
 23 min. per ep.          1070
 25 min. per ep.           846
 30 min. per ep.           746
 2 min.                    744
                          ...
 1 hr. 52 min. per ep.       1
 2 hr. 33 min.               1
 2 hr. 21 min.               1
 19 sec.                     1
 55 sec. per ep.             1
 Name: Duration, Length: 313, dtype: int64,
 PG-13 - Teens 13 or older         6068
 G - All Ages                      5753
 PG - Children                     1448
 Rx - Hentai                       1343
 R - 17+ (violence & profanity)    1144
 R+ - Mild Nudity                   995
 No raiting                         527
 Name: Rating, dtype: int64,
 0        1549
 12978       6
 5297        6
 6413        5
 11806       5
          ...
 7489        1
 5177        1
 5786        1
 6889        1
 13980       1
 Name: Ranked, Length: 10458, dtype: int64,
 11039    6
 9611     5
 13393    5
 4161     5
 13583    5
         ..
 288      1
 8878     1
 6593     1
 10573    1
 14514    1
 Name: Popularity, Length: 11650, dtype: int64,
 142      31
 120      30
 104      28
 126      27
 136      27
          ..
 972       1
 1070      1
 44920     1
 55650     1
 10722     1
 Name: Members, Length: 9407, dtype: int64,
 0        5615
 1        1782
 2         926
 3         660
 4         500
          ...
 7246        1
 14335       1
 11530       1
 9653        1
 3056        1
 Name: Favorites, Length: 1540, dtype: int64,
 6        446
 7        403
 9        371
 8        358
 10       345
         ...
 7137       1
 4725       1
 12885      1
 2889       1
 9848       1
 Name: Watching, Length: 3579, dtype: int64,
 0        331
 53        60
 87        58
 64        55
 1         55
         ...
 1692       1
 20569      1
 42350      1
 36933      1
 7207       1
 Name: Completed, Length: 7821, dtype: int64,
 2        723
 0        698
 1        657
 3        634
 4        620
         ...
 6708       1
 1533       1
 477        1
 15929      1
 467        1
 Name: On-Hold, Length: 2915, dtype: int64,
 35       201
 36       192
 34       189
 38       184
 37       182
         ...
 7288       1
 3723       1
 14710      1
 4110       1
 2192       1
 Name: Dropped, Length: 3035, dtype: int64,
 26        78
 33        73
 25        69
 21        66
 32        65
           ..
 49174      1
 27009      1
 43484      1
 274277     1
 2674       1
 Name: Plan to Watch, Length: 6965, dtype: int64,
 4        930
 5        895
 6        749
 3        738
 7        612
         ...
 1906       1
 17409      1
 2384       1
 24258      1
 1305       1
 Name: Score-10, Length: 3379, dtype: int64,
 0        2931
 1        1234
 2         743
 3         506
 4         451
          ...
 48887       1
 27640       1
 14490       1
 7208        1
 12054       1
 Name: Score-9, Length: 3645, dtype: int64,
 1       1182
 0       1150
 2        859
 3        593
 4        482
         ...
 1053       1
 2680       1
 1022       1
 1482       1
 878        1
 Name: Score-8, Length: 4515, dtype: int64,
 2        594
 1        582
 3        542
 4        445
 7        351
         ...
 26159      1
 6426       1
 74753      1
 32013      1
 2526       1
 Name: Score-7, Length: 4932, dtype: int64,
 2        406
 3        405
 4        382
 5        360
 6        333
         ...
 6498       1
 15547      1
 1194       1
 2284       1
 782        1
 Name: Score-6, Length: 4235, dtype: int64,
 0        358
 6        307
 5        302
 7        289
 4        276
         ...
 14182      1
 2715       1
 5598       1
 9370       1
 5688       1
 Name: Score-5, Length: 3287, dtype: int64,
 0       749
 1       602
 2       556
 4       476
 3       464
        ...
 3350      1
 3349      1
 2432      1
 2371      1
 1294      1
 Name: Score-4, Length: 2234, dtype: int64,
 0       1068
 1        944
 2        770
 3        635
 4        572
         ...
 957        1
 4105       1
 2162       1
 1192       1
 1477       1
 Name: Score-3, Length: 1506, dtype: int64,
 0       1349
 1       1099
 2        905
 3        862
 4        699
         ...
 511        1
 4057       1
 606        1
 559        1
 762        1
 Name: Score-2, Length: 1110, dtype: int64,
 4       939
 3       869
 5       843
 6       771
 7       703
        ...
 974       1
 753       1
 603       1
 6030      1
 478       1
 Name: Score-1, Length: 1083, dtype: int64]